### ISSUE TITLE
Plugin compatibility with `css-loader`@6.x

### ISSUE THREAD

**Issue by Semigradsky** [birdofpreyru/babel-plugin-react-css-modules#13]
New `css-loader` major version was relised.

generateScopedName currently generates different hash than `css-loader`@6.x

**Comment by birdofpreyru** [comment]
Yeap. I had a brief look at `css-loader` changes, there is quite a large update of classname generation logic, including migration from some dependencies they used in that logic before to some utilities from Webpack core. Thus, as it is definitely not a one-liner fix, it will take me some time to figure it out and update this library. Taking into account other stuff I am busy with, probably it will require me a few weeks.

**Comment by birdofpreyru** [comment]
I think, `v6.2.0` should do the trick, however I am not able to carefully test it, as it turns out I am not depending on the altered logic anymore, and `css-loader` update from `5.2.7` to `6.2.0` does not break code in my projects.

The deal is: it turns out some time ago I got so frustrated with often alterations of classname generation by `css-loader` (which required extra testing efforts, and test updates each time) that I just have frozen it in my projects, and it was so successful, that I even forgot about it since. Thus, I my recommendation for everyone is to do the same.

My workaround is the following. I wrote [this small module](https://github.com/birdofpreyru/react-utils/blob/82cc1c33900915232638744deabe9ee0152ec537/config/shared/utils.js), which in nutshell is a copy of classname generation logic from earlier versions of `css-loader` and this plugin. This module exports `getLocalIdent()` and `generateScopedName()` functions (in my case two slightly different variants of the latter one, for dev and prod environments).

I then pass:
- `getLocalIdent()` into `modules.getLocalIdent` option of `css-loader` (alongside `modules.localIdentName`);
- `generateScopedName()` into `generateScopedName` option of this `babel-plugin-react-css-module`;
- `generateScopedName()` into `generateScopedName` option of similar `@dr.pogodin/babel-plugin-css-modules-transform` plugin I am additionally using for SSR.

With such setup all modules dealing with CSS classnames get the same configuration, which is mostly independent from small alterations of default behavior done by `css-loader` maintainers now and then.

**Comment by birdofpreyru** [comment]
Hmm... double-checked, I believe both 00b54f3 and fcbacca are a part of `v6.2.0` which is tagged at the later commit 15759e81da7d530c9d117ef3b195292b699f689c (I have CI/CD set up to release from the version according to where the tag is, not the commit where the version was bumped in `package.json`).

If it does not work for you it is either (i) I missed some detail, and it will take more time to write some additional tests, and then to fix the problem; or (ii) it might be that you override some of [these options](https://github.com/birdofpreyru/babel-plugin-react-css-modules/blob/15759e81da7d530c9d117ef3b195292b699f689c/src/requireCssModule.js#L128-L140) in your Webpack config. For now I just hard-coded them to Webpack's defaults. It is technically easy to expose them as plugin options (mostly required to update option validations, and README), but I had no time nor much motivation to spent time on it so far.

**Comment by Semigradsky** [comment]
> 00b54f3 and fcbacca are not released.

Oh, sorry, I was wrong.

About my configuration:
```js
const cssSelectorPattern = '[path]__[local]___[hash:base64:5]'

const config = {
  ...
  // babel loader configuration
  plugins: [
   ['@dr.pogodin/babel-plugin-react-css-modules', {
      filetypes: {
        '.scss': {
          syntax: 'postcss-scss',
        },
      },
      exclude: 'node_modules',
      generateScopedName: cssSelectorPattern,
      webpackHotModuleReloading: true,
      autoResolveMultipleImports: true,
    }],
  ],
  ...
    {
      loader: 'css-loader',
      options: {
        modules: {
          localIdentName: cssSelectorPattern,
        },
        sourceMap: true,
      },
    },
  ...
}
```
So I just pass pattern to `generateScopedName` and `localIdentName` properties, there are no any special options.

This worked for `css-loader`@5.x, but for `css-loader`@6.x it generates different hashes.

**Comment by birdofpreyru** [comment]
@Semigradsky I just tried (e82e09cdbb5e5033680416ab3262fe24eb50477d) to emulate your config in a very goofy test, which checks that classnames output by `css-loader@6.1.0` match outputs by this plugin; and in principle they seem to match, as long as the `[path]` is resolved relative to the same folder in both cases. Can you double-check whether it works for you if you remove `[path]` from the class name template? So far my best guess is that recent updates of `css-loader` changed that resolution logic, and I am missing that change inside this plugin.

**Comment by Semigradsky** [comment]
🔴  With pattern `'[path]__[local]___[hash:base64:5]'`:
babel-plugin-react-css-modules: `src-ui-report-title-__report-title___2qWwh`
css-loader: `src-ui-report-title-__report-title____V1eA`

---
✔️  With pattern `'[local]___[hash:base64:5]'`:
babel-plugin-react-css-modules: `report-title____V1eA`
css-loader: `report-title____V1eA`
